#!/usr/bin/env python3
"""Integration tests for postconditions referencing codeBlock-computed variables.

This test suite explores how the validation hierarchy handles postconditions that
reference variables computed in codeBlocks (not direct item outcomes).

Background (from thesis - comprehensive_validation.tex):
    The validation hierarchy has three levels:
    1. Per-item validation: Uses B (domain constraints only) - fast, independent
    2. Global validation: Uses F = B ∧ ∧(P_i ⇒ Q_i) - checks overall satisfiability
    3. Path-based validation: Accumulated constraints - detects dead code

    All three levels use B := ∧_i D_i(S_i) which is domain constraints ONLY.
    CodeBlock assignments create SSA behavioral constraints stored separately.

Test scenario (codeblock_postcondition.qml):
    - q1: outcome in [0, 10], codeBlock: var1 = q1.outcome
    - q2: outcome in [10, 20], codeBlock: var1 = var1 + q2.outcome
    - q4: postcondition: var1 - 1000 > q2.outcome

    Mathematical analysis:
    - var1 = q1.outcome + q2.outcome, so var1 in [10, 30]
    - max(var1 - 1000) = -970, min(q2.outcome) = 10
    - var1 - 1000 > q2.outcome is NEVER satisfiable

Gap analysis:
    None of the three validation levels currently detect this because:
    - Per-item: Uses B only, var1 is unconstrained → reports CONSTRAINING
    - Global: Uses B only, F is vacuously satisfiable → reports SAT
    - Path-based: Uses B only, same issue

    The SSA constraints (var1 = q1.outcome + q2.outcome) are generated by
    StaticBuilder but NOT included in the base B used for validation.

    For postconditions referencing computed variables, the behavioral constraints
    SHOULD be included to give meaningful classification.
"""

import unittest
import pytest
from pathlib import Path

from askalot_qml.core.qml_loader import QMLLoader
from askalot_qml.models.qml_state import QMLState
from askalot_qml.core.qml_engine import QMLEngine
from askalot_qml.z3 import ItemClassifier, GlobalFormula


FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"


def load_qml_fixture(filename: str) -> QMLState:
    """Load a QML fixture file and return QMLState."""
    loader = QMLLoader(schema_path=None)
    qml_path = FIXTURES_DIR / filename
    data = loader.load_from_path(str(qml_path))
    return QMLState(data)


def create_engine(filename: str) -> QMLEngine:
    """Load a QML fixture and create QMLEngine."""
    state = load_qml_fixture(filename)
    return QMLEngine(state)


@pytest.mark.integration
class TestStaticBuilderTracksCodeBlockVariables(unittest.TestCase):
    """
    Verify that StaticBuilder correctly tracks codeBlock variable assignments.

    This is working correctly - SSA versions and constraints ARE being generated.
    The issue is that these constraints are not used in validation.
    """

    def setUp(self):
        self.engine = create_engine("codeblock_postcondition.qml")
        self.builder = self.engine.static_builder

    def test_ssa_versions_created_for_var1(self):
        """StaticBuilder creates SSA versions for var1 from codeBlocks."""
        self.assertIn(
            "var1",
            self.builder.version_map,
            "var1 should be tracked in SSA version map"
        )
        # Should have multiple versions (from codeInit, q1, q2)
        self.assertGreaterEqual(
            self.builder.version_map.get("var1", -1),
            1,
            "var1 should have at least 2 versions (from q1 and q2 codeBlocks)"
        )

    def test_z3_variables_created_for_var1_versions(self):
        """Z3 variables are created for each SSA version of var1."""
        var1_vars = [name for name in self.builder.z3_vars.keys() if name.startswith("var1_")]
        self.assertGreater(
            len(var1_vars),
            0,
            "Should have SSA versions of var1 in z3_vars"
        )

    def test_behavioral_constraints_created(self):
        """StaticBuilder creates behavioral constraints from codeBlock assignments."""
        self.assertGreater(
            len(self.builder.constraints),
            0,
            "StaticBuilder should create constraints from codeBlock assignments"
        )

    def test_domain_constraints_created(self):
        """Domain constraints are created for items with min/max."""
        self.assertGreater(
            len(self.builder.domain_constraints),
            0,
            "Domain constraints should exist for items with min/max"
        )


@pytest.mark.integration
class TestPerItemValidationWithComputedVariables(unittest.TestCase):
    """
    Test per-item validation behavior with computed variables.

    With the fix, per-item validation now uses full_base which includes
    codeBlock constraints. This allows proper bounds checking for computed
    variables like var1 = q1.outcome + q2.outcome.
    """

    def setUp(self):
        self.engine = create_engine("codeblock_postcondition.qml")
        self.builder = self.engine.static_builder
        self.classifier = ItemClassifier(self.builder)
        self.classifications = self.classifier.classify_all_items()

    def test_per_item_reports_infeasible_with_codeblock_constraints(self):
        """
        Per-item validation reports INFEASIBLE because var1 is bounded by codeBlocks.

        With full_base including codeBlock constraints:
        - var1 = q1.outcome + q2.outcome
        - var1 in [10, 30] (since q1 in [0,10], q2 in [10,20])
        - var1 - 1000 in [-990, -970]
        - q2.outcome in [10, 20]
        - var1 - 1000 > q2.outcome is NEVER satisfiable
        """
        q4_classification = self.classifications.get("q4", {})
        postcond = q4_classification.get("postcondition", {})
        invariant = postcond.get("invariant", "UNKNOWN")

        print(f"\nq4 postcondition invariant: {invariant}")
        print("Expected: INFEASIBLE (var1 bounded by codeBlock constraints)")

        self.assertEqual(
            invariant,
            "INFEASIBLE",
            f"With codeBlock constraints, q4 postcondition should be INFEASIBLE, got {invariant}"
        )

    def test_q_globally_false_is_true_with_codeblock_constraints(self):
        """
        q_globally_false is True because var1's bounds make Q unsatisfiable.

        q_globally_false := UNSAT(full_base ∧ Q)
        With var1 bounded by codeBlock constraints, Q can never be satisfied.
        """
        q4_classification = self.classifications.get("q4", {})
        postcond = q4_classification.get("postcondition", {})
        global_flags = postcond.get("global", {})

        q_globally_false = global_flags.get("q_globally_false", None)
        print(f"\nq4 q_globally_false: {q_globally_false}")

        self.assertTrue(
            q_globally_false,
            "q_globally_false should be True with codeBlock constraints (var1 bounded)"
        )


@pytest.mark.integration
class TestGlobalValidationWithComputedVariables(unittest.TestCase):
    """
    Test global validation behavior with computed variables.

    Global validation uses F = B ∧ ∧(P_i ⇒ Q_i) where B is domain-only.
    """

    def setUp(self):
        self.engine = create_engine("codeblock_postcondition.qml")
        self.builder = self.engine.static_builder

    def test_global_formula_reports_sat(self):
        """
        Global formula reports SAT because var1 is unconstrained.

        F = B ∧ ∧(P_i ⇒ Q_i)
        With var1 unconstrained, we can pick var1=2000 to satisfy Q_4.
        """
        global_formula = GlobalFormula(self.builder)
        result = global_formula.check()

        print(f"\nGlobal formula status: {result.status}")
        print(f"Global formula satisfiable: {result.satisfiable}")

        # Current behavior: SAT (var1 unconstrained)
        # If behavioral constraints were included: would depend on the formula
        self.assertTrue(
            result.satisfiable,
            f"Global formula should be SAT with domain-only base, got {result.status}"
        )


@pytest.mark.integration
class TestCodeBlockConstraintsSeparation(unittest.TestCase):
    """
    Test that codeBlock constraints are properly separated from pre/postcondition
    constraints and correctly used in validation.

    This validates the fix where:
    - codeblock_constraints: SSA assignments from codeBlocks
    - constraints: pre/postcondition implications (kept separate)
    - get_full_base(): domain + codeblock_constraints (NOT pre/post)
    """

    def setUp(self):
        self.engine = create_engine("codeblock_postcondition.qml")
        self.builder = self.engine.static_builder

    def test_codeblock_constraints_separate_from_behavioral(self):
        """
        CodeBlock constraints should be stored separately from pre/postcondition constraints.
        """
        # codeblock_constraints should have the SSA assignments
        # var1_0 = 0 (from codeInit)
        # var1_1 = item_q1 (from q1 codeBlock)
        # var1_2 = var1_1 + item_q2 (from q2 codeBlock)
        self.assertEqual(
            len(self.builder.codeblock_constraints),
            3,
            f"Should have 3 codeBlock constraints (init + q1 + q2), got {len(self.builder.codeblock_constraints)}"
        )

    def test_postcondition_not_in_codeblock_constraints(self):
        """
        Postcondition implications should NOT be in codeblock_constraints.
        """
        # The postcondition for q4 should be in self.constraints, not codeblock_constraints
        codeblock_str = str(self.builder.codeblock_constraints)
        self.assertNotIn(
            "1000",
            codeblock_str,
            "Postcondition (var1 - 1000 > q2.outcome) should not be in codeblock_constraints"
        )

    def test_full_base_uses_codeblock_constraints(self):
        """
        get_full_base() should include codeblock_constraints for proper validation.
        """
        full_base_str = str(self.builder.get_full_base())

        # Should include SSA assignment var1_1 == item_q1
        self.assertIn("var1_1", full_base_str, "full_base should reference var1_1")

        # Should include SSA assignment var1_2 == var1_1 + item_q2
        self.assertIn("var1_2", full_base_str, "full_base should reference var1_2")


@pytest.mark.integration
class TestDebugOutput(unittest.TestCase):
    """Debug tests to inspect what's being built."""

    def setUp(self):
        self.engine = create_engine("codeblock_postcondition.qml")
        self.builder = self.engine.static_builder

    def test_print_debug_dump(self):
        """Print debug info for manual inspection."""
        debug_output = self.builder.debug_dump()
        print("\n" + "="*60)
        print("STATIC BUILDER DEBUG DUMP")
        print("="*60)
        print(debug_output)
        print("="*60)

        self.assertIn("var1", debug_output, "Debug dump should mention var1")

    def test_print_all_constraints(self):
        """Print all constraints for manual inspection."""
        print("\n" + "="*60)
        print("Z3 CONSTRAINTS ANALYSIS")
        print("="*60)

        print(f"\nDomain constraints ({len(self.builder.domain_constraints)}):")
        print("  (These define valid value ranges for item outcomes)")
        for i, c in enumerate(self.builder.domain_constraints):
            print(f"  {i}: {c}")

        print(f"\nCodeBlock constraints ({len(self.builder.codeblock_constraints)}):")
        print("  (These define SSA relationships from codeBlock assignments)")
        for i, c in enumerate(self.builder.codeblock_constraints):
            print(f"  {i}: {c}")

        print(f"\nPre/Post constraints ({len(self.builder.constraints)}):")
        print("  (These are precondition/postcondition implications)")
        for i, c in enumerate(self.builder.constraints):
            print(f"  {i}: {c}")

        print(f"\nZ3 variables for SSA versions:")
        for name, var in sorted(self.builder.z3_vars.items()):
            print(f"  {name}: {var}")

        print("="*60)

    def test_print_classification_results(self):
        """Print classification results for all items."""
        classifier = ItemClassifier(self.builder)
        classifications = classifier.classify_all_items()

        print("\n" + "="*60)
        print("ITEM CLASSIFICATION RESULTS")
        print("="*60)

        for item_id, classification in classifications.items():
            precond = classification.get("precondition", {})
            postcond = classification.get("postcondition", {})
            global_flags = postcond.get("global", {})

            print(f"\n{item_id}:")
            print(f"  Precondition: {precond.get('status', 'N/A')}")
            print(f"  Postcondition: {postcond.get('invariant', 'N/A')}")
            print(f"  q_globally_false: {global_flags.get('q_globally_false', 'N/A')}")
            print(f"  q_globally_true: {global_flags.get('q_globally_true', 'N/A')}")

        print("="*60)


if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
