#!/usr/bin/env python3
"""Unit tests for QMLDiagram JSON Graph IR generation.

This test suite verifies the JSON graph intermediate representation
generated by generate_base_graph().

## Coverage Areas:

### Graph IR Structure (7 tests)
- Empty questionnaire returns valid structure
- Single item node properties
- Multiple items with topological chain
- Variable nodes and assignment edges
- Precondition nodes and dependency edges
- Postcondition nodes and dependency edges
- Rich metadata (item_type, control_type)

### Graph Coloring (1 test)
- Analysis coloring produces correct classes map

### Cycle Handling (3 tests)
- Cycle metadata in graph IR
- Cycle edges in graph IR (with chain edges for vertical layout)
- Cycle nodes override Z3 classification

### Cycle Visualization (4 tests)
- Exactly one backward arc per cycle (normalized to file order)
- Collateral items included in cycle_nodes metadata
- in_cycle flag on topological edges between affected items
- Collateral items colored as 'cycle'

These unit tests verify the graph IR that drives the QML Explorer
diagram in Armiger, ensuring cycle visualization is clear and accurate.
"""

import unittest
import pytest
from askalot_qml.models.qml_state import QMLState
from askalot_qml.core.qml_topology import QMLTopology
from askalot_qml.core.qml_diagram import QMLDiagram
from askalot_qml.z3.static_builder import StaticBuilder


def create_questionnaire(items_data: list, code_init: str = '') -> QMLState:
    """Helper to create QMLState from item definitions."""
    return QMLState({
        'title': 'Test Questionnaire',
        'codeInit': code_init,
        'blocks': [{'id': 'b1', 'title': 'Block 1'}],
        'items': [
            {
                'id': item['id'],
                'blockId': 'b1',
                'kind': item.get('kind', 'Question'),
                'title': item.get('title', f"Question {item['id']}"),
                **{k: v for k, v in item.items() if k not in ('id', 'title', 'kind')}
            }
            for item in items_data
        ]
    })


def create_diagram(state: QMLState) -> QMLDiagram:
    """Helper to create QMLDiagram from QMLState."""
    builder = StaticBuilder(state)
    topology = QMLTopology(state, builder)
    return QMLDiagram(topology, state)


@pytest.mark.unit
@pytest.mark.diagram
class TestGraphIRStructure(unittest.TestCase):
    """Tests for JSON graph IR structure."""

    def test_empty_questionnaire(self):
        """Empty questionnaire returns valid graph with empty lists."""
        state = QMLState({'title': 'Empty', 'blocks': [], 'items': []})
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        self.assertIn('nodes', graph)
        self.assertIn('edges', graph)
        self.assertIn('metadata', graph)
        self.assertEqual(graph['nodes'], [])
        self.assertEqual(graph['edges'], [])
        self.assertFalse(graph['metadata']['has_cycles'])

    def test_single_item_node(self):
        """Single item produces one node with correct properties."""
        state = create_questionnaire([{'id': 'q1', 'title': 'First Question'}])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        item_nodes = [n for n in graph['nodes'] if n['type'] == 'item']
        self.assertEqual(len(item_nodes), 1)
        self.assertEqual(item_nodes[0]['id'], 'q1')
        self.assertEqual(item_nodes[0]['label'], 'q1: First Question')
        self.assertEqual(item_nodes[0]['type'], 'item')
        self.assertEqual(item_nodes[0]['group'], 'b1')

    def test_topological_chain_edges(self):
        """Multiple items produce topological chain edges."""
        state = create_questionnaire([
            {'id': 'q1'},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3'}
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        topo_edges = [e for e in graph['edges'] if e['type'] == 'topological']
        # Should have chain edges connecting items in topological order
        self.assertTrue(len(topo_edges) >= 2)

        # Verify chain connectivity
        sources = {e['source'] for e in topo_edges}
        targets = {e['target'] for e in topo_edges}
        item_ids = {n['id'] for n in graph['nodes'] if n['type'] == 'item'}
        self.assertTrue(sources.issubset(item_ids))
        self.assertTrue(targets.issubset(item_ids))

    def test_variable_nodes(self):
        """Variable assignments create variable nodes and edges."""
        state = create_questionnaire([
            {'id': 'q1', 'codeBlock': 'score = 10'},
            {'id': 'q2', 'codeBlock': 'score = score + 5'}
        ], code_init='score = 0')
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        var_nodes = [n for n in graph['nodes'] if n['type'] == 'variable']
        self.assertTrue(len(var_nodes) >= 1)
        var_ids = {n['id'] for n in var_nodes}
        self.assertIn('var_score', var_ids)

        # Variable assignment edges: variable -> item (variable points to items that modify it)
        var_edges = [e for e in graph['edges'] if e['type'] == 'variable_assignment']
        self.assertTrue(len(var_edges) >= 1)
        # At least one edge from var_score to an item
        var_score_edges = [e for e in var_edges if e['source'] == 'var_score']
        self.assertTrue(len(var_score_edges) >= 1)

    def test_precondition_nodes(self):
        """Preconditions create precondition nodes with containment and dependency edges."""
        state = create_questionnaire([
            {'id': 'q1'},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]}
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        precond_nodes = [n for n in graph['nodes'] if n['type'] == 'precondition']
        self.assertEqual(len(precond_nodes), 1)
        self.assertEqual(precond_nodes[0]['id'], 'q2_precond_0')
        self.assertEqual(precond_nodes[0]['owner'], 'q2')
        self.assertIn('q1.outcome == 1', precond_nodes[0]['label'])

        # Containment edge: q2_precond_0 -> q2 (precondition points to owner)
        containment = [e for e in graph['edges']
                       if e['type'] == 'containment' and e['source'] == 'q2_precond_0']
        self.assertEqual(len(containment), 1)
        self.assertEqual(containment[0]['target'], 'q2')

        # Dependency edge: q2_precond_0 -> q1
        dep_edges = [e for e in graph['edges']
                     if e['type'] == 'dependency' and e['source'] == 'q2_precond_0']
        dep_targets = {e['target'] for e in dep_edges}
        self.assertIn('q1', dep_targets)

    def test_postcondition_nodes(self):
        """Postconditions create postcondition nodes with edges."""
        state = create_questionnaire([
            {'id': 'q1', 'postcondition': [{'predicate': 'q1.outcome > 0', 'hint': 'Must be positive'}]}
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        postcond_nodes = [n for n in graph['nodes'] if n['type'] == 'postcondition']
        self.assertEqual(len(postcond_nodes), 1)
        self.assertEqual(postcond_nodes[0]['id'], 'q1_postcond_0')
        self.assertEqual(postcond_nodes[0]['owner'], 'q1')

        # Containment edge: q1_postcond_0 -> q1 (postcondition points to owner)
        containment = [e for e in graph['edges']
                       if e['type'] == 'containment' and e['source'] == 'q1_postcond_0']
        self.assertEqual(len(containment), 1)
        self.assertEqual(containment[0]['target'], 'q1')

    def test_rich_metadata(self):
        """Item nodes carry kind and control type metadata."""
        state = create_questionnaire([
            {
                'id': 'q1',
                'kind': 'Question',
                'input': {'control': 'Radio', 'labels': {1: 'Yes', 2: 'No'}}
            }
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        item_node = graph['nodes'][0]
        self.assertEqual(item_node['item_type'], 'question')
        self.assertEqual(item_node['control_type'], 'radio')


@pytest.mark.unit
@pytest.mark.diagram
class TestGraphColoring(unittest.TestCase):
    """Tests for graph coloring."""

    def test_validation_coloring_classes(self):
        """Validation coloring adds correct classes map."""
        state = create_questionnaire([
            {'id': 'q1'},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]}
        ])

        from askalot_qml.z3.item_classifier import ItemClassifier
        builder = StaticBuilder(state)
        topology = QMLTopology(state, builder)
        diagram = QMLDiagram(topology, state)
        classifier = ItemClassifier(builder)
        classifications = classifier.classify_all_items()

        graph = diagram.generate_base_graph()
        colored = diagram.apply_validation_coloring(graph, classifications=classifications)

        self.assertIn('classes', colored)
        self.assertEqual(colored['classes']['q1'], 'always')
        self.assertEqual(colored['classes']['q2'], 'conditional')

@pytest.mark.unit
@pytest.mark.diagram
class TestGraphIRCycles(unittest.TestCase):
    """Tests for cycle handling in graph IR."""

    def test_cycle_metadata(self):
        """Cycles are recorded in metadata."""
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]}
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        self.assertTrue(graph['metadata']['has_cycles'])
        self.assertTrue(len(graph['metadata']['cycle_nodes']) > 0)

    def test_cycle_edges(self):
        """Cycle edges appear in edge list alongside chain edges for vertical layout."""
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]}
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        cycle_edges = [e for e in graph['edges'] if e['type'] == 'cycle']
        self.assertTrue(len(cycle_edges) > 0)

        # Chain edges must exist even with cycles (fallback to QML file order)
        chain_edges = [e for e in graph['edges'] if e['type'] == 'topological']
        self.assertTrue(len(chain_edges) > 0)

    def test_cycle_nodes_override_classification(self):
        """Cycle nodes get class 'cycle' regardless of Z3 classification."""
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3'},  # Not in cycle
        ])

        from askalot_qml.z3.item_classifier import ItemClassifier
        builder = StaticBuilder(state)
        topology = QMLTopology(state, builder)
        diagram = QMLDiagram(topology, state)
        classifier = ItemClassifier(builder)
        classifications = classifier.classify_all_items()

        graph = diagram.generate_base_graph()
        colored = diagram.apply_validation_coloring(graph, classifications=classifications)

        # Cycle nodes must have 'cycle' class
        cycle_node_ids = set(graph['metadata']['cycle_nodes'])
        self.assertTrue(len(cycle_node_ids) > 0)
        for node_id in cycle_node_ids:
            self.assertEqual(colored['classes'][node_id], 'cycle')

        # Non-cycle node retains its Z3 classification
        self.assertNotEqual(colored['classes']['q3'], 'cycle')


@pytest.mark.unit
@pytest.mark.diagram
class TestCycleVisualization(unittest.TestCase):
    """Tests for cycle edge normalization and affected-item coloring."""

    def test_exactly_one_backward_arc(self):
        """Each cycle produces exactly one backward arc (last→first in file order).

        Cycle: q1 → q2 → q3 → q1. File order: q1, q2, q3.
        Expected: one backward cycle edge q3→q1, forward edges handled
        by topological chain (q1→q2, q2→q3 marked in_cycle).
        """
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q3.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        cycle_edges = [e for e in graph['edges'] if e['type'] == 'cycle']
        # Exactly one backward arc: last→first in file order
        backward = [e for e in cycle_edges
                    if graph['metadata']['cycle_nodes'].index(e['target'])
                    < graph['metadata']['cycle_nodes'].index(e['source'])]
        self.assertEqual(len(backward), 1)
        self.assertEqual(backward[0]['target'], 'q1')

    def test_only_cycle_members_in_cycle_nodes(self):
        """cycle_nodes metadata contains only DFS cycle path members,
        not downstream items that depend on them.

        Cycle: q1 → q2 → q1. q3 depends on q2 (downstream). q4 independent.
        """
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q4'},
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        cycle_nodes = set(graph['metadata']['cycle_nodes'])
        # q1, q2 are cycle members
        self.assertIn('q1', cycle_nodes)
        self.assertIn('q2', cycle_nodes)
        # q3 depends on q2 but is NOT in the cycle itself
        self.assertNotIn('q3', cycle_nodes)
        # q4 is independent
        self.assertNotIn('q4', cycle_nodes)

    def test_in_cycle_flag_on_cycle_member_edges(self):
        """Topological edges between cycle members get in_cycle=True.
        Edges connecting a cycle member to a non-member do NOT get the flag.

        Cycle: q1 → q2 → q3 → q1. All three are cycle members.
        """
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q3.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
        ])
        diagram = create_diagram(state)
        graph = diagram.generate_base_graph()

        topo_edges = [e for e in graph['edges'] if e['type'] == 'topological']
        in_cycle_edges = [e for e in topo_edges if e.get('in_cycle')]
        # All topological edges connect cycle members → in_cycle
        self.assertEqual(len(in_cycle_edges), 2)
        # All in_cycle edges have both endpoints as cycle members
        cycle_nodes = set(graph['metadata']['cycle_nodes'])
        for edge in in_cycle_edges:
            self.assertIn(edge['source'], cycle_nodes)
            self.assertIn(edge['target'], cycle_nodes)

    def test_only_cycle_members_colored_as_cycle(self):
        """Only cycle members get 'cycle' class. Downstream items keep
        their Z3 classification.

        Cycle: q1 → q2 → q1. q3 depends on q2 (downstream). q4 independent.
        """
        from askalot_qml.z3.item_classifier import ItemClassifier
        state = create_questionnaire([
            {'id': 'q1', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q2', 'precondition': [{'predicate': 'q1.outcome == 1'}]},
            {'id': 'q3', 'precondition': [{'predicate': 'q2.outcome == 1'}]},
            {'id': 'q4'},
        ])
        builder = StaticBuilder(state)
        topology = QMLTopology(state, builder)
        diagram = QMLDiagram(topology, state)
        classifier = ItemClassifier(builder)
        classifications = classifier.classify_all_items()

        graph = diagram.generate_base_graph()
        colored = diagram.apply_validation_coloring(graph, classifications=classifications)

        # Cycle members get 'cycle' class
        self.assertEqual(colored['classes']['q1'], 'cycle')
        self.assertEqual(colored['classes']['q2'], 'cycle')
        # Downstream q3 keeps its Z3 classification (not 'cycle')
        self.assertNotEqual(colored['classes']['q3'], 'cycle')
        # Independent q4 also not 'cycle'
        self.assertNotEqual(colored['classes']['q4'], 'cycle')


if __name__ == '__main__':
    unittest.main()
